### PR TITLE
Add weather, 24 hour clock setting and image file loading.

### PR DESCRIPTION
**Pull request by carolosf**

### CODE REVIEW

**Comment by spezifisch** [comment]
Thanks for the PR! I actually wanted support for sending images for a while so this comes in handy!

I'll merge it as soon as I can after running test with my Pixoo.

**Comment by carolosf** [comment]
> Thanks for the PR! I actually wanted support for sending images for a while so this comes in handy!
> 
> I'll merge it as soon as I can after running test with my Pixoo.

Sure - take your time.

For it to be complete it probably needs some methods in pixoo.py not sure what your plans are for the class APIs so left them out.

Please also note that it borrows from https://github.com/johsam/timebox-evo-rest/blob/master/evo/encoder.py and added to image.py another GPL 3 project - probably worth mentioning on the readme if you decide to keep it. 

Feel free to change as needed.

The weather/climate additions are worth keeping if you decide to re-implement the image parser.

The main thing is that it is working!

I am also working on running it in Docker and my Raspberry Pi 4.

**Review by spezifisch — APPROVED** [review]

**Comment by spezifisch** [comment]
Your `test.png` looks fine on my Pixoo, so I merged your first commit.

> Please also note that it borrows from https://github.com/johsam/timebox-evo-rest/blob/master/evo/encoder.py and added to image.py another GPL 3 project - probably worth mentioning on the readme if you decide to keep it.

I'm looking into that right now so that we honor its license.

> For it to be complete it probably needs some methods in pixoo.py not sure what your plans are for the class APIs so left them out.
 
My big goal is to control the Pixoo with a [home-assistant](https://github.com/home-assistant) plugin so that I can see temperature sensors and other notifications. For this I was going to add an HTTP API that can be controlled from that plugin.

> I am also working on running it in Docker and my Raspberry Pi 4.

Great! I'm planning to use a Raspberry Pi 3 with Docker for this, too. It would be neat if the pulseaudio parts could be easily disabled because the Pixoo doesn't have audio.

**Comment by spezifisch** [comment]
To be compliant with their GPLv3 I split https://github.com/spezifisch/divo/blob/41c94366b7cb6362032f581e6f4a21c48d3ebbae/divo/evo_encoder.py and https://github.com/spezifisch/divo/blob/41c94366b7cb6362032f581e6f4a21c48d3ebbae/divo/evo_pixmap.py so that they can get their own header crediting the original author.

As it seems to be [best practice](https://opensource.stackexchange.com/a/4582) I also added GPL headers to the other files and added you as author where you modified code. Let me know if I missed anything.

I would mark this PR "merged" but that would pull your docker changes in which I can't yet test.

**Comment by carolosf** [comment]
> Great! I'm planning to use a Raspberry Pi 3 with Docker for this, too. It would be neat if the pulseaudio parts could be easily disabled because the Pixoo doesn't have audio.
I didn't really want to support pulseaudio but my timebox-evo didn't want to connect on the raspberry pi without the pulseaudio stuff. It looks like the timebox-evo connects as a bluetooth speaker. Any idea if the pixoo shows up as a speaker also?

BTW I think the timebox only supports bluetooth 5 btw and I think only Raspberry Pi 4 has bluetooth 5.

Let me know if the pixoo works without pulseaudio or if you see any bluez error when trying to connect on your raspberry pi after the `bluetoothctl connect` command. If you get a bluez error for me it was because of pulseaudio and you can see any errors by running `journalctl`.

Happy to close the pull request and thanks for making the needed changes for GPL.

**Comment by carolosf** [comment]
Found an interesting API doc for the pixoo 64 which has a Http API:
http://doc.divoom-gz.com/web/#/12?page_id=89

**Pull request closed without merging**
